# Training config
config = {
    'bins': 128,
    'discrete': False,
    'dynamics': 'bicycle',
    'env_type': 'planning',
    'extractor': 'ExtractObsForAWM',
    'feature_extractor': 'KeyExtractor',
    'feature_extractor_kwargs': {'final_hidden_layers': 512,
                                 'hidden_layers': {
                                     'xyyawv': 256,
                                     'sdc_speed': 128,
                                     'heading': 128,
                                     'roadgraph_map': 256,
                                     'traffic_lights': 128,
                                     'proxy_goal':64
                                     },
                                 'keys': [
                                    'xyyawv',
                                    'sdc_speed',
                                    'heading',
                                    'roadgraph_map',
                                    'traffic_lights',
                                        ],
                                 'kwargs': {
                                     'heading': {'radius': 10},
                                     }
                                 },
    'freq_eval': 10,
    'freq_save': 5,
    'filter_fun_name': 'inter_filter_fun',
    'filter_fun_args': {},
    'include_sdc_paths': False,
    'key': 42,
    'loss': 'logprob',
    'lr': 3e-4,
    'lr_cosine': True,
    'incremental_learning': False,
    'lr_max': 1e-3,
    'lr_transition_epoch': 80,
    'lr_scheduler': False,
    "max_grad_norm": 0.5,
    'max_num_obj': 128,
    'max_num_rg_points': 20000,
    'num_envs': 256, # This is batch size, set to lower if getting OOM
    'num_envs_eval': 1,
    "num_epochs": 80,
    'num_steps': 80,
    'obs_mask':  None,
    'obs_mask_kwargs': None,
    'roadgraph_top_k': 2000,
    'shuffle_seed': 123,
    'shuffle_buffer_size': 1000,
    'total_timesteps': 100,
    'num_files': 1000,
    'training_path': 'gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/tf_example/training/training_tfexample.tfrecord@1000',
    'validation_path': 'gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/tf_example/validation/validation_tfexample.tfrecord@150',
    'dataset_cache': True, # Whether to cache the dataset. Should be either (True, False or a string) for (in memory, no caching, or to a file on disk).
    'planning_horizon': 10,
    'num_imagined_rollouts': 4,
    'use_planner_for_train': False,
    'select_action_from_full_gmm': False,
    }